apiVersion: v1
kind: Service
metadata:
  name: gameboard
  labels:
    app: gameboard
spec:
  selector:
    app: gameboard
  ports:
  - port: 20333
    targetPort: 20333
    nodePort: 30333
  clusterIP: 10.254.8.200
  type: NodePort
